# Generated by Django 5.1 on 2024-09-10 08:51

from django.db import migrations, transaction


def populate_database(apps, schema_editor):
    Item = apps.get_model('sk', 'Item')
    with open('sk/migrations/db.txt') as f:
        with transaction.atomic():
            for e in f.readlines():
                Item.objects.create(
                    SKU=e,
                    n=0,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_database)
    ]
